language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: H0IwBkSjFwdh8/DSsen4YJUeFD56b+qoUTsyJq0fIoY4WkBOzXeJqapyzhU5X5aieBmWRvkCH7fuUHGDTkr3t0d6M/gGwTSX6LhqKAJ2JbDbVXvUmi+SrHmSimmbGYh6hnY06k7qZisSZdwIOLnGBGW2K1wp9IjYrR9YGqK+O793sBHmtR2H8qExvTFFtKuhzYJJeUSrxH2NplkFnnqffCwFqYMnjao4dL3HUp1m+MmTdCutO3asjtQwoLf2tKPMjE56Fs+HBWoJ2utwDze0V4RE9O5jVwWmifAoawZlXUv079ccfJZRIaukWJjRdTRM+edNo4oTmUhB7JlHL3KFcKmMrbn7kTmrm4AsCokw9PZAz8jCo+QOVXIMeADJ5Dou75akmhH7Y417cADeivPP8YzGfpGYinjGk/UmJNF9J+wFdcKVB2wWDJNjwx17l6QhMIVtmFffRiWT4ls1JAshZICAubqJsw5fmWLB2aRg815+VlqygH4H3ynxXvNxK4Zyn/BSaKXRfbH1/UWdQ0BDFRKSt5RXtTaibPEYuh7ZVgqdmXvJGIK+NUXplgT5pMQo7cpH+AgTLvWpHTHo6f4Dl+k4hOv9EVmxb9xi6zIc6MPOPK7C7f2rvY8yCmk/8Y/4mts686iz8v+b3iaOORRnP3Jc3o4wcATsIGlL2LfrVcg=
  - secure: 2Hzjs2HINJfxy0NFtUn2dl59ubBHAH1nSsAq4IEgQfrc/qeahoCpSXNvTFd3CFhHnrzdB8pKidCHz7gKNXKWycB2drfLT/uxrg+swLSFtLAiZLw0UfRQDKtYCaNhD/gpLdKrk0hqV3AZHf7GJv2TJQDvSzMV/ix4cxHVLyMbenBBWmo3HI8Rx1cof8odyCU58Bujr+46+XiP1GBX6iDPGtnW64pViYxV98kCKip7fFatsYZPcQajbAMqyo7wJCSQcIAGpwKWYzz97v4VG7ZfLsvz76Q70Bx2a0ZZ76/5ZBbxH0hXiVTlRQ0beLgsoq/N4YIu79BpUwS4Irike7YE2RVlceQdU93e5El3xcwTAFWCAr4tXYx2CMgcQM22i/SFHWc7ZXtHE+CAW9/sfkqn/xup/88UMqJpbxSKnJeGMRvcE/kh4JugUvlH7I3lRDLzFvOW3FK5yHgG/6FY+65JuK6qXUqbCEOQAiBzqIWz9TB2QeHvce3sBz6KaWK3l7juQOzJCirEJ9wOBHE2lWD6NksCj73wa3D8e01wMD9xdnrpCzlLrXqYVO4hIOF5oyAoSgM17KG0XqJfYBuFRN+FjjL24kJdNEpjgGogBLSCJ0epXVknGybMvZOGEBZ3cnnZE2caRIP7Ae/Lwb3BUEIbeSDMBPPx0PuYqo9EHTuWW8A=
